# Generated by Django 3.0.7 on 2020-06-09 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('green', 'green'), ('red', 'red')], default=django.utils.timezone.now, max_length=80, verbose_name='Kategori'),
            preserve_default=False,
        ),
    ]
