# Generated by Django 3.0.7 on 2020-06-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='article_img',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Görsel'),
        ),
    ]
