# Generated by Django 3.0.7 on 2020-06-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-add_date']},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-comment_date']},
        ),
    ]
