# Generated by Django 3.0.7 on 2020-06-19 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200619_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={},
        ),
    ]
