# Generated by Django 3.0.7 on 2020-06-19 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20200619_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commet_author',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Yorumcu'),
            preserve_default=False,
        ),
    ]
