# Generated by Django 3.0.7 on 2020-06-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20200619_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-comment_date']},
        ),
    ]
