# Generated by Django 3.0.7 on 2020-06-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20200619_1204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
