# Generated by Django 3.0.7 on 2020-06-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commet_author',
            new_name='comment_author',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='commet_content',
            new_name='comment_content',
        ),
    ]
