# Generated by Django 3.0.7 on 2020-06-19 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0021_comments_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='article',
        ),
        migrations.CreateModel(
            name='Commander',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentcontent', models.CharField(max_length=200, verbose_name='Yorum')),
                ('commentdate', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.Articles', verbose_name='Makale')),
                ('commentauthor', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
