# Generated by Django 3.0.7 on 2020-06-19 10:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_auto_20200619_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.Articles', verbose_name='Makale'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Commander',
        ),
    ]
