# Generated by Django 3.0.7 on 2020-06-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_auto_20200619_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_author',
            field=models.CharField(max_length=200, verbose_name='Yorum'),
        ),
    ]
