# Generated by Django 3.0.7 on 2020-06-25 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0031_articles_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='cc',
            field=models.ManyToManyField(blank=True, related_name='cc', to=settings.AUTH_USER_MODEL),
        ),
    ]
