# Generated by Django 3.0.7 on 2020-07-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0036_auto_20200708_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('deneme', 'deneme'), ('aksiyon', 'aksiyon')], max_length=80, verbose_name='Kategori'),
        ),
    ]
