# Generated by Django 3.0.7 on 2020-07-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0037_auto_20200708_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('green', 'green'), ('red', 'red')], default=0, max_length=80, verbose_name='Kategori'),
            preserve_default=False,
        ),
    ]
