# Generated by Django 3.0.7 on 2020-07-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0042_articles_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='slug',
        ),
    ]
