# Generated by Django 3.0.7 on 2020-07-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0047_auto_20200709_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(max_length=300, unique=True),
        ),
    ]
