# Generated by Django 3.0.7 on 2020-07-10 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0049_visit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='article',
            new_name='arti',
        ),
    ]
